In [632]:
# Dependencies
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
# Import and establish Base for which classes will be constructed 
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, Float, BIGINT
import sqlite3

In [633]:
# Store filepath in a variable
state_coordinates = "/Users/admin/Desktop/us_energy/us-energy-analysis/assets/data/state_coordinates/statelatlong.csv"

In [634]:
# Read our Data file with the pandas library
state_coordinates_df = pd.read_csv(state_coordinates, encoding="ISO-8859-1")

In [635]:
# Show just the header
state_coordinates_df.head()

  State   Latitude   Longitude        City
0    AL  32.601011  -86.680736     Alabama
1    AK  61.302501 -158.775020      Alaska
2    AZ  34.168219 -111.930907     Arizona
3    AR  34.751928  -92.131378    Arkansas
4    CA  37.271875 -119.270415  California

In [636]:
# Name the Index Column
state_coordinates_df.index.names = ['id']
state_coordinates_df.head()

   State   Latitude   Longitude        City
id
0     AL  32.601011  -86.680736     Alabama
1     AK  61.302501 -158.775020      Alaska
2     AZ  34.168219 -111.930907     Arizona
3     AR  34.751928  -92.131378    Arkansas
4     CA  37.271875 -119.270415  California

In [637]:
# Create a new Engine instance
engine = create_engine('sqlite:///assets/db/us_energy.sqlite', echo=False)

In [638]:
# Import Dataframe into SQLite
state_coordinates_df.to_sql('state_coordinates', con=engine)

In [639]:
# Execute a Query to check if the table has been imported successfully 
engine.execute('SELECT * FROM state_coordinates').fetchall()

[(0, 'AL', 32.601011199999995, -86.6807365, 'Alabama'),
 (1, 'AK', 61.3025006, -158.7750198, 'Alaska'),
 (2, 'AZ', 34.1682185, -111.930907, 'Arizona'),
 (3, 'AR', 34.7519275, -92.13137840000002, 'Arkansas'),
 (4, 'CA', 37.2718745, -119.2704153, 'California'),
 (5, 'CO', 38.9979339, -105.55056699999999, 'Colorado'),
 (6, 'CT', 41.518783500000005, -72.75750699999999, 'Connecticut'),
 (7, 'DE', 39.145251, -75.41892059999999, 'Delaware'),
 (8, 'DC', 38.899348700000004, -77.0145666, 'District of Columbia'),
 (9, 'FL', 27.9757279, -83.8330166, 'Florida'),
 (10, 'GA', 32.6781248, -83.22297569999999, 'Georgia'),
 (11, 'HI', 20.46, -157.505, 'Hawaii'),
 (12, 'ID', 45.4945756, -114.1424303, 'Idaho'),
 (13, 'IL', 39.739318, -89.504139, 'Illinois'),
 (14, 'IN', 39.7662195, -86.441277, 'Indiana'),
 (15, 'IA', 41.9383166, -93.389798, 'Iowa'),
 (16, 'KS', 38.4987789, -98.32007790000002, 'Kansas'),
 (17, 'KY', 37.8222935, -85.76823990000001, 'Kentucky'),
 (18, 'LA', 30.9733766, -91.42990970000001, 'Louisiana'),
 (19, 'ME', 45.2185133, -69.0148656, 'Maine'),
 (20, 'MD', 38.806352399999994, -77.2684162, 'Maryland'),
 (21, 'MA', 42.062939799999995, -71.718067, 'Massachusetts'),
 (22, 'MI', 44.9435598, -86.41580490000001, 'Michigan'),
 (23, 'MN', 46.4418595, -93.3655146, 'Minnesota'),
 (24, 'MS', 32.5851062, -89.8772196, 'Mississippi'),
 (25, 'MO', 38.3046615, -92.437099, 'Missouri'),
 (26, 'MT', 46.6797995, -110.04478300000001, 'Montana'),
 (27, 'NE', 41.5008195, -99.680902, 'Nebraska'),
 (28, 'NV', 38.502032, -117.0230604, 'Nevada'),
 (29, 'NH', 44.00123060000001, -71.57992309999999, 'New Hampshire'),
 (30, 'NJ', 40.1430058, -74.7311156, 'New Jersey'),
 (31, 'NM', 34.1662325, -106.02606850000001, 'New Mexico'),
 (32, 'NY', 40.7056258, -73.97968, 'New York'),
 (33, 'NC', 35.2145629, -79.8912675, 'North Carolina'),
 (34, 'ND', 47.467881899999995, -100.3022655, 'North Dakota'),
 (35, 'OH', 40.1903624, -82.6692525, 'Ohio'),
 (36, 'OK', 35.309765399999996, -98.71655849999999, 'Oklahoma'),
 (37, 'OR', 44.1419049, -120.5380993, 'Oregon'),
 (38, 'PA', 40.99459279999999, -77.6046984, 'Pennsylvania'),
 (39, 'RI', 41.5827282, -71.5064508, 'Rhode Island'),
 (40, 'SC', 33.62505, -80.9470381, 'South Carolina'),
 (41, 'SD', 44.2126995, -100.24716409999999, 'South Dakota'),
 (42, 'TN', 35.830521000000005, -85.97859890000001, 'Tennessee'),
 (43, 'TX', 31.1693363, -100.0768425, 'Texas'),
 (44, 'UT', 39.4997605, -111.547028, 'Utah'),
 (45, 'VT', 43.8717545, -72.4477828, 'Vermont'),
 (46, 'VA', 38.0033855, -79.4587861, 'Virginia'),
 (47, 'WA', 38.899348700000004, -77.0145665, 'Washington'),
 (48, 'WV', 38.920170500000005, -80.1816905, 'West Virginia'),
 (49, 'WI', 44.7862968, -89.82670490000001, 'Wisconsin'),
 (50, 'WY', 43.000325, -107.5545669, 'Wyoming')]

In [640]:
# Closing all currently checked in database connections.
engine.dispose()

In [641]:
# Create a Connection object 
con = sqlite3.connect('/Users/admin/Desktop/us_energy/us-energy-analysis/assets/db/us_energy.sqlite')

In [642]:
# Cursor object to fetch results
cur = con.cursor()

In [643]:
# Disable Foreign Key
cur.execute('PRAGMA foreign_keys=off')

In [644]:
# Open a Transaction
cur.execute('BEGIN TRANSACTION;')

In [645]:
# Rename the "state_coordinates" to "old_table"
cur.execute('ALTER TABLE state_coordinates RENAME TO old_table;')

In [646]:
# Create a new table with the same name "state_coordinates"
cur.execute('CREATE TABLE state_coordinates (id Integer PRIMARY KEY NOT NULL,State Text, Latitude Float, Longitude Float, US_State String);')

In [647]:
# Insert "old_table" data into the newly created table "state_coordinates"
cur.execute('INSERT INTO state_coordinates SELECT * FROM old_table;')

In [648]:
# Delete the "old_table"
cur.execute('DROP TABLE old_table;')

In [649]:
# Commit the changes to the database "us_energy.sqlite"
cur.execute('COMMIT TRANSACTION;')

In [650]:
# Enabling the Foreign Key
cur.execute('PRAGMA foreign_keys=on;')

In [651]:
# Close the database connection
cur.close()
conn.close()

In [652]:
# Execute a Query to check if the table has been imported successfully 
engine.execute('SELECT * FROM state_coordinates').fetchall()

[(0, 'AL', 32.601011199999995, -86.6807365, 'Alabama'),
 (1, 'AK', 61.3025006, -158.7750198, 'Alaska'),
 (2, 'AZ', 34.1682185, -111.930907, 'Arizona'),
 (3, 'AR', 34.7519275, -92.13137840000002, 'Arkansas'),
 (4, 'CA', 37.2718745, -119.2704153, 'California'),
 (5, 'CO', 38.9979339, -105.55056699999999, 'Colorado'),
 (6, 'CT', 41.518783500000005, -72.75750699999999, 'Connecticut'),
 (7, 'DE', 39.145251, -75.41892059999999, 'Delaware'),
 (8, 'DC', 38.899348700000004, -77.0145666, 'District of Columbia'),
 (9, 'FL', 27.9757279, -83.8330166, 'Florida'),
 (10, 'GA', 32.6781248, -83.22297569999999, 'Georgia'),
 (11, 'HI', 20.46, -157.505, 'Hawaii'),
 (12, 'ID', 45.4945756, -114.1424303, 'Idaho'),
 (13, 'IL', 39.739318, -89.504139, 'Illinois'),
 (14, 'IN', 39.7662195, -86.441277, 'Indiana'),
 (15, 'IA', 41.9383166, -93.389798, 'Iowa'),
 (16, 'KS', 38.4987789, -98.32007790000002, 'Kansas'),
 (17, 'KY', 37.8222935, -85.76823990000001, 'Kentucky'),
 (18, 'LA', 30.9733766, -91.42990970000001, 'Louisiana'),
 (19, 'ME', 45.2185133, -69.0148656, 'Maine'),
 (20, 'MD', 38.806352399999994, -77.2684162, 'Maryland'),
 (21, 'MA', 42.062939799999995, -71.718067, 'Massachusetts'),
 (22, 'MI', 44.9435598, -86.41580490000001, 'Michigan'),
 (23, 'MN', 46.4418595, -93.3655146, 'Minnesota'),
 (24, 'MS', 32.5851062, -89.8772196, 'Mississippi'),
 (25, 'MO', 38.3046615, -92.437099, 'Missouri'),
 (26, 'MT', 46.6797995, -110.04478300000001, 'Montana'),
 (27, 'NE', 41.5008195, -99.680902, 'Nebraska'),
 (28, 'NV', 38.502032, -117.0230604, 'Nevada'),
 (29, 'NH', 44.00123060000001, -71.57992309999999, 'New Hampshire'),
 (30, 'NJ', 40.1430058, -74.7311156, 'New Jersey'),
 (31, 'NM', 34.1662325, -106.02606850000001, 'New Mexico'),
 (32, 'NY', 40.7056258, -73.97968, 'New York'),
 (33, 'NC', 35.2145629, -79.8912675, 'North Carolina'),
 (34, 'ND', 47.467881899999995, -100.3022655, 'North Dakota'),
 (35, 'OH', 40.1903624, -82.6692525, 'Ohio'),
 (36, 'OK', 35.309765399999996, -98.71655849999999, 'Oklahoma'),
 (37, 'OR', 44.1419049, -120.5380993, 'Oregon'),
 (38, 'PA', 40.99459279999999, -77.6046984, 'Pennsylvania'),
 (39, 'RI', 41.5827282, -71.5064508, 'Rhode Island'),
 (40, 'SC', 33.62505, -80.9470381, 'South Carolina'),
 (41, 'SD', 44.2126995, -100.24716409999999, 'South Dakota'),
 (42, 'TN', 35.830521000000005, -85.97859890000001, 'Tennessee'),
 (43, 'TX', 31.1693363, -100.0768425, 'Texas'),
 (44, 'UT', 39.4997605, -111.547028, 'Utah'),
 (45, 'VT', 43.8717545, -72.4477828, 'Vermont'),
 (46, 'VA', 38.0033855, -79.4587861, 'Virginia'),
 (47, 'WA', 38.899348700000004, -77.0145665, 'Washington'),
 (48, 'WV', 38.920170500000005, -80.1816905, 'West Virginia'),
 (49, 'WI', 44.7862968, -89.82670490000001, 'Wisconsin'),
 (50, 'WY', 43.000325, -107.5545669, 'Wyoming')]

In [653]:
# Assign final_combine_table.csv to final_combine_table
final_combine_table = "/Users/admin/Desktop/us_energy/us-energy-analysis/assets/data/EIA_Project_Data/final_combine_table.csv"

In [654]:
# Create a Connection object 
con = sqlite3.connect('/Users/admin/Desktop/us_energy/us-energy-analysis/assets/db/us_energy.sqlite')

In [655]:
# Read our Data file with the pandas library
final_combine_table_df = pd.read_csv(final_combine_table, encoding="ISO-8859-1")

In [656]:
# Show just the header
final_combine_table_df.head()

,State,Year,Total_co2_emission,CO2_Unit,Average_Price,Price_Unit,resident_population,Pop_Unit,Total_energy,ENERGY_Unit,Total_renewable_energy,Renew_Unit
0,AL,2016,115.088298,million metric tons CO2,14.81,Dollars per million Btu,4865,Thousand,1124482,Billion Btu,235494,Billion Btu
1,AL,2015,120.142812,million metric tons CO2,15.68,Dollars per million Btu,4853,Thousand,1269743,Billion Btu,261340,Billion Btu
2,AL,2014,123.161802,million metric tons CO2,18.62,Dollars per million Btu,4842,Thousand,1367345,Billion Btu,268551,Billion Btu
3,AL,2013,120.908517,million metric tons CO2,18.89,Dollars per million Btu,4830,Thousand,1478402,Billion Btu,310608,Billion Btu
4,AL,2012,123.201027,million metric tons CO2,19.86,Dollars per million Btu,4816,Thousand,1443558,Billion Btu,241822,Billion Btu

In [657]:
# Rename the Index Column
final_combine_table_df.index.names = ['id']
final_combine_table_df.head()

,State,Year,Total_co2_emission,CO2_Unit,Average_Price,Price_Unit,resident_population,Pop_Unit,Total_energy,ENERGY_Unit,Total_renewable_energy,Renew_Unit
id,,,,,,,,,,,,
0,AL,2016,115.088298,million metric tons CO2,14.81,Dollars per million Btu,4865,Thousand,1124482,Billion Btu,235494,Billion Btu
1,AL,2015,120.142812,million metric tons CO2,15.68,Dollars per million Btu,4853,Thousand,1269743,Billion Btu,261340,Billion Btu
2,AL,2014,123.161802,million metric tons CO2,18.62,Dollars per million Btu,4842,Thousand,1367345,Billion Btu,268551,Billion Btu
3,AL,2013,120.908517,million metric tons CO2,18.89,Dollars per million Btu,4830,Thousand,1478402,Billion Btu,310608,Billion Btu
4,AL,2012,123.201027,million metric tons CO2,19.86,Dollars per million Btu,4816,Thousand,1443558,Billion Btu,241822,Billion Btu

In [658]:
# Import Dataframe into SQLite
final_combine_table_df.to_sql('final_combine_table', con=engine)

In [659]:
# Execute a Query to check if the table has been imported successfully 
engine.execute('SELECT * FROM final_combine_table').fetchall()

[(0, 'AL', 2016, 115.088298, 'million metric tons CO2', 14.81, 'Dollars per million Btu', 4865, 'Thousand', 1124482, 'Billion Btu', 235494, 'Billion Btu'),
 (1, 'AL', 2015, 120.142812, 'million metric tons CO2', 15.68, 'Dollars per million Btu', 4853, 'Thousand', 1269743, 'Billion Btu', 261340, 'Billion Btu'),
 (2, 'AL', 2014, 123.161802, 'million metric tons CO2', 18.62, 'Dollars per million Btu', 4842, 'Thousand', 1367345, 'Billion Btu', 268551, 'Billion Btu'),
 (3, 'AL', 2013, 120.908517, 'million metric tons CO2', 18.89, 'Dollars per million Btu', 4830, 'Thousand', 1478402, 'Billion Btu', 310608, 'Billion Btu'),
 (4, 'AL', 2012, 123.201027, 'million metric tons CO2', 19.86, 'Dollars per million Btu', 4816, 'Thousand', 1443558, 'Billion Btu', 241822, 'Billion Btu'),
 (5, 'AL', 2011, 129.930038, 'million metric tons CO2', 20.06, 'Dollars per million Btu', 4799, 'Thousand', 1410745, 'Billion Btu', 254867, 'Billion Btu'),
 (6, 'AL', 2010, 132.767419, 'million metric tons CO2', 17.8, 'Dollars per million Btu', 4785, 'Thousand', 1429505, 'Billion Btu', 240913, 'Billion Btu'),
 (7, 'AL', 2009, 120.100202, 'million metric tons CO2', 16.55, 'Dollars per million Btu', 4758, 'Thousand', 1449253, 'Billion Btu', 264487, 'Billion Btu'),
 (8, 'AL', 2008, 139.628142, 'million metric tons CO2', 19.22, 'Dollars per million Btu', 4718, 'Thousand', 1482792, 'Billion Btu', 233379, 'Billion Btu'),
 (9, 'AL', 2007, 147.430252, 'million metric tons CO2', 16.06, 'Dollars per million Btu', 4673, 'Thousand', 1408105, 'Billion Btu', 228160, 'Billion Btu'),
 (10, 'AL', 2006, 145.782018, 'million metric tons CO2', 14.96, 'Dollars per million Btu', 4629, 'Thousand', 1413493, 'Billion Btu', 266153, 'Billion Btu'),
 (11, 'AL', 2005, 143.332446, 'million metric tons CO2', 13.56, 'Dollars per million Btu', 4570, 'Thousand', 1502435, 'Billion Btu', 279600, 'Billion Btu'),
 (12, 'AL', 2004, 141.664798, 'million metric tons CO2', 11.27, 'Dollars per million Btu', 4531, 'Thousand', 1544007, 'Billion Btu', 290697, 'Billion Btu'),
 (13, 'AL', 2003, 139.358938, 'million metric tons CO2', 9.98, 'Dollars per million Btu', 4503, 'Thousand', 1521048, 'Billion Btu', 283428, 'Billion Btu'),
 (14, 'AL', 2002, 138.490682, 'million metric tons CO2', 9.16, 'Dollars per million Btu', 4480, 'Thousand', 1486477, 'Billion Btu', 252689, 'Billion Btu'),
 (15, 'AL', 2001, 133.630128, 'million metric tons CO2', 9.45, 'Dollars per million Btu', 4468, 'Thousand', 1484590, 'Billion Btu', 251523, 'Billion Btu'),
 (16, 'AL', 2000, 142.242532, 'million metric tons CO2', 8.78, 'Dollars per million Btu', 4452, 'Thousand', 1539601, 'Billion Btu', 263303, 'Billion Btu'),
 (17, 'AL', 1999, 136.122518, 'million metric tons CO2', 7.58, 'Dollars per million Btu', 4430, 'Thousand', 1578642, 'Billion Btu', 290195, 'Billion Btu'),
 (18, 'AL', 1998, 133.741224, 'million metric tons CO2', 7.33, 'Dollars per million Btu', 4405, 'Thousand', 1672363, 'Billion Btu', 317065, 'Billion Btu'),
 (19, 'AL', 1997, 134.474292, 'million metric tons CO2', 7.52, 'Dollars per million Btu', 4368, 'Thousand', 1708520, 'Billion Btu', 299675, 'Billion Btu'),
 (20, 'AK', 2016, 115.088298, 'million metric tons CO2', 16.63, 'Dollars per million Btu', 742, 'Thousand', 1433116, 'Billion Btu', 19428, 'Billion Btu'),
 (21, 'AK', 2015, 120.142812, 'million metric tons CO2', 18.82, 'Dollars per million Btu', 738, 'Thousand', 1424762, 'Billion Btu', 19209, 'Billion Btu'),
 (22, 'AK', 2014, 123.161802, 'million metric tons CO2', 24.83, 'Dollars per million Btu', 736, 'Thousand', 1474609, 'Billion Btu', 19826, 'Billion Btu'),
 (23, 'AK', 2013, 120.908517, 'million metric tons CO2', 24.92, 'Dollars per million Btu', 737, 'Thousand', 1513406, 'Billion Btu', 18664, 'Billion Btu'),
 (24, 'AK', 2012, 123.201027, 'million metric tons CO2', 25.44, 'Dollars per million Btu', 730, 'Thousand', 1563461, 'Billion Btu', 17719, 'Billion Btu'),
 (25, 'AK', 2011, 129.930038, 'million metric tons CO2', 25.13, 'Dollars per million Btu', 722, 'Thousand', 1642015, 'Billion Btu', 15762, 'Billion Btu'),
 (26, 'AK', 2010, 132.767419, 'million metric tons CO2', 20.37, 'Dollars per million Btu', 714, 'Thousand', 1738219, 'Billion Btu', 16537, 'Billion Btu'),
 (27, 'AK', 2009, 120.100202, 'million metric tons CO2', 18.22, 'Dollars per million Btu', 699, 'Thousand', 1853317, 'Billion Btu', 15685, 'Billion Btu'),
 (28, 'AK', 2008, 139.628142, 'million metric tons CO2', 23.91, 'Dollars per million Btu', 687, 'Thousand', 1932755, 'Billion Btu', 12913, 'Billion Btu'),
 (29, 'AK', 2007, 147.430252, 'million metric tons CO2', 17.94, 'Dollars per million Btu', 680, 'Thousand', 2051639, 'Billion Btu', 14037, 'Billion Btu'),
 (30, 'AK', 2006, 145.782018, 'million metric tons CO2', 16.61, 'Dollars per million Btu', 675, 'Thousand', 2100329, 'Billion Btu', 13298, 'Billion Btu'),
 (31, 'AK', 2005, 143.332446, 'million metric tons CO2', 13.99, 'Dollars per million Btu', 667, 'Thousand', 2415039, 'Billion Btu', 15866, 'Billion Btu'),
 (32, 'AK', 2004, 141.664798, 'million metric tons CO2', 11.07, 'Dollars per million Btu', 659, 'Thousand', 2512619, 'Billion Btu', 18416, 'Billion Btu'),
 (33, 'AK', 2003, 139.358938, 'million metric tons CO2', 9.08, 'Dollars per million Btu', 648, 'Thousand', 2660210, 'Billion Btu', 19374, 'Billion Btu'),
 (34, 'AK', 2002, 138.490682, 'million metric tons CO2', 7.78, 'Dollars per million Btu', 642, 'Thousand', 2658368, 'Billion Btu', 17922, 'Billion Btu'),
 (35, 'AK', 2001, 133.630128, 'million metric tons CO2', 8.18, 'Dollars per million Btu', 634, 'Thousand', 2630790, 'Billion Btu', 16974, 'Billion Btu'),
 (36, 'AK', 2000, 142.242532, 'million metric tons CO2', 8.03, 'Dollars per million Btu', 628, 'Thousand', 2645900, 'Billion Btu', 12204, 'Billion Btu'),
 (37, 'AK', 1999, 136.122518, 'million metric tons CO2', 6.17, 'Dollars per million Btu', 625, 'Thousand', 2797459, 'Billion Btu', 10212, 'Billion Btu'),
 (38, 'AK', 1998, 133.741224, 'million metric tons CO2', 5.8, 'Dollars per million Btu', 620, 'Thousand', 3067133, 'Billion Btu', 13291, 'Billion Btu'),
 (39, 'AK', 1997, 134.474292, 'million metric tons CO2', 6.74, 'Dollars per million Btu', 613, 'Thousand', 3331780, 'Billion Btu', 14994, 'Billion Btu'),
 (40, 'AZ', 2016, 115.088298, 'million metric tons CO2', 20.65, 'Dollars per million Btu', 6945, 'Thousand', 593132, 'Billion Btu', 130858, 'Billion Btu'),
 (41, 'AZ', 2015, 120.142812, 'million metric tons CO2', 22.47, 'Dollars per million Btu', 6834, 'Thousand', 614524, 'Billion Btu', 120715, 'Billion Btu'),
 (42, 'AZ', 2014, 123.161802, 'million metric tons CO2', 25.77, 'Dollars per million Btu', 6734, 'Thousand', 631852, 'Billion Btu', 114133, 'Billion Btu'),
 (43, 'AZ', 2013, 120.908517, 'million metric tons CO2', 25.89, 'Dollars per million Btu', 6635, 'Thousand', 591410, 'Billion Btu', 98874, 'Billion Btu'),
 (44, 'AZ', 2012, 123.201027, 'million metric tons CO2', 26.19, 'Dollars per million Btu', 6557, 'Thousand', 594938, 'Billion Btu', 93042, 'Billion Btu'),
 (45, 'AZ', 2011, 129.930038, 'million metric tons CO2', 25.37, 'Dollars per million Btu', 6473, 'Thousand', 615323, 'Billion Btu', 105082, 'Billion Btu'),
 (46, 'AZ', 2010, 132.767419, 'million metric tons CO2', 22.32, 'Dollars per million Btu', 6408, 'Thousand', 579778, 'Billion Btu', 77419, 'Billion Btu'),
 (47, 'AZ', 2009, 120.100202, 'million metric tons CO2', 20.14, 'Dollars per million Btu', 6343, 'Thousand', 563061, 'Billion Btu', 73117, 'Billion Btu'),
 (48, 'AZ', 2008, 139.628142, 'million metric tons CO2', 23.95, 'Dollars per million Btu', 6280, 'Thousand', 576899, 'Billion Btu', 88850, 'Billion Btu'),
 (49, 'AZ', 2007, 147.430252, 'million metric tons CO2', 20.87, 'Dollars per million Btu', 6168, 'Thousand', 538976, 'Billion Btu', 79355, 'Billion Btu'),
 (50, 'AZ', 2006, 145.782018, 'million metric tons CO2', 19.7, 'Dollars per million Btu', 6029, 'Thousand', 511638, 'Billion Btu', 80772, 'Billion Btu'),
 (51, 'AZ', 2005, 143.332446, 'million metric tons CO2', 17.87, 'Dollars per million Btu', 5839, 'Thousand', 611615, 'Billion Btu', 78333, 'Billion Btu'),
 (52, 'AZ', 2004, 141.664798, 'million metric tons CO2', 15.36, 'Dollars per million Btu', 5652, 'Thousand', 653416, 'Billion Btu', 81376, 'Billion Btu'),
 (53, 'AZ', 2003, 139.358938, 'million metric tons CO2', 13.86, 'Dollars per million Btu', 5510, 'Thousand', 643921, 'Billion Btu', 83079, 'Billion Btu'),
 (54, 'AZ', 2002, 138.490682, 'million metric tons CO2', 12.39, 'Dollars per million Btu', 5396, 'Thousand', 689876, 'Billion Btu', 86880, 'Billion Btu'),
 (55, 'AZ', 2001, 133.630128, 'million metric tons CO2', 12.82, 'Dollars per million Btu', 5273, 'Thousand', 684436, 'Billion Btu', 90513, 'Billion Btu'),
 (56, 'AZ', 2000, 142.242532, 'million metric tons CO2', 12.94, 'Dollars per million Btu', 5161, 'Thousand', 705102, 'Billion Btu', 100776, 'Billion Btu'),
 (57, 'AZ', 1999, 136.122518, 'million metric tons CO2', 11.24, 'Dollars per million Btu', 5024, 'Thousand', 691730, 'Billion Btu', 114876, 'Billion Btu'),
 (58, 'AZ', 1998, 133.741224, 'million metric tons CO2', 10.83, 'Dollars per million Btu', 4883, 'Thousand', 693182, 'Billion Btu', 126648, 'Billion Btu'),
 (59, 'AZ', 1997, 134.474292, 'million metric tons CO2', 11.76, 'Dollars per million Btu', 4737, 'Thousand', 706668, 'Billion Btu', 141607, 'Billion Btu'),
 (60, 'AR', 2016, 115.088298, 'million metric tons CO2', 14.6, 'Dollars per million Btu', 2990, 'Thousand', 1130117, 'Billion Btu', 117959, 'Billion Btu'),
 (61, 'AR', 2015, 120.142812, 'million metric tons CO2', 15.87, 'Dollars per million Btu', 2978, 'Thousand', 1319553, 'Billion Btu', 115780, 'Billion Btu'),
 (62, 'AR', 2014, 123.161802, 'million metric tons CO2', 18.86, 'Dollars per million Btu', 2968, 'Thousand', 1440726, 'Billion Btu', 116541, 'Billion Btu'),
 (63, 'AR', 2013, 120.908517, 'million metric tons CO2', 19.29, 'Dollars per million Btu', 2960, 'Thousand', 1434515, 'Billion Btu', 116746, 'Billion Btu'),
 (64, 'AR', 2012, 123.201027, 'million metric tons CO2', 19.82, 'Dollars per million Btu', 2952, 'Thousand', 1466389, 'Billion Btu', 111220, 'Billion Btu'),
 (65, 'AR', 2011, 129.930038, 'million metric tons CO2', 19.59, 'Dollars per million Btu', 2940, 'Thousand', 1385343, 'Billion Btu', 119758, 'Billion Btu'),
 (66, 'AR', 2010, 132.767419, 'million metric tons CO2', 16.86, 'Dollars per million Btu', 2922, 'Thousand', 1250560, 'Billion Btu', 123317, 'Billion Btu'),
 (67, 'AR', 2009, 120.100202, 'million metric tons CO2', 15.64, 'Dollars per million Btu', 2897, 'Thousand', 1007445, 'Billion Btu', 124205, 'Billion Btu'),
 (68, 'AR', 2008, 139.628142, 'million metric tons CO2', 19.96, 'Dollars per million Btu', 2875, 'Thousand', 761611, 'Billion Btu', 123354, 'Billion Btu'),
 (69, 'AR', 2007, 147.430252, 'million metric tons CO2', 16.68, 'Dollars per million Btu', 2849, 'Thousand', 593930, 'Billion Btu', 120733, 'Billion Btu'),
 (70, 'AR', 2006, 145.782018, 'million metric tons CO2', 15.78, 'Dollars per million Btu', 2822, 'Thousand', 572694, 'Billion Btu', 99990, 'Billion Btu'),
 (71, 'AR', 2005, 143.332446, 'million metric tons CO2', 14.46, 'Dollars per million Btu', 2781, 'Thousand', 484786, 'Billion Btu', 112451, 'Billion Btu'),
 (72, 'AR', 2004, 141.664798, 'million metric tons CO2', 11.96, 'Dollars per million Btu', 2750, 'Thousand', 503242, 'Billion Btu', 112915, 'Billion Btu'),
 (73, 'AR', 2003, 139.358938, 'million metric tons CO2', 10.23, 'Dollars per million Btu', 2725, 'Thousand', 478389, 'Billion Btu', 107905, 'Billion Btu'),
 (74, 'AR', 2002, 138.490682, 'million metric tons CO2', 9.39, 'Dollars per million Btu', 2706, 'Thousand', 469275, 'Billion Btu', 108618, 'Billion Btu'),
 (75, 'AR', 2001, 133.630128, 'million metric tons CO2', 10.2, 'Dollars per million Btu', 2692, 'Thousand', 462934, 'Billion Btu', 94001, 'Billion Btu'),
 (76, 'AR', 2000, 142.242532, 'million metric tons CO2', 9.47, 'Dollars per million Btu', 2679, 'Thousand', 447405, 'Billion Btu', 108634, 'Billion Btu'),
 (77, 'AR', 1999, 136.122518, 'million metric tons CO2', 7.9, 'Dollars per million Btu', 2652, 'Thousand', 461717, 'Billion Btu', 110822, 'Billion Btu'),
 (78, 'AR', 1998, 133.741224, 'million metric tons CO2', 7.71, 'Dollars per million Btu', 2626, 'Thousand', 492864, 'Billion Btu', 114927, 'Billion Btu'),
 (79, 'AR', 1997, 134.474292, 'million metric tons CO2', 8.24, 'Dollars per million Btu', 2601, 'Thousand', 534963, 'Billion Btu', 124045, 'Billion Btu'),
 (80, 'CA', 2016, 115.088298, 'million metric tons CO2', 19.9, 'Dollars per million Btu', 39209, 'Thousand', 2431124, 'Billion Btu', 903915, 'Billion Btu'),
 (81, 'CA', 2015, 120.142812, 'million metric tons CO2', 21.88, 'Dollars per million Btu', 38953, 'Thousand', 2361858, 'Billion Btu', 719166, 'Billion Btu'),
 (82, 'CA', 2014, 123.161802, 'million metric tons CO2', 25.51, 'Dollars per million Btu', 38625, 'Thousand', 2383159, 'Billion Btu', 721739, 'Billion Btu'),
 (83, 'CA', 2013, 120.908517, 'million metric tons CO2', 25.08, 'Dollars per million Btu', 38281, 'Thousand', 2372246, 'Billion Btu', 719604, 'Billion Btu'),
 (84, 'CA', 2012, 123.201027, 'million metric tons CO2', 25.13, 'Dollars per million Btu', 37961, 'Thousand', 2317708, 'Billion Btu', 677346, 'Billion Btu'),
 (85, 'CA', 2011, 129.930038, 'million metric tons CO2', 24.5, 'Dollars per million Btu', 37642, 'Thousand', 2632438, 'Billion Btu', 806477, 'Billion Btu'),
 (86, 'CA', 2010, 132.767419, 'million metric tons CO2', 21.13, 'Dollars per million Btu', 37321, 'Thousand', 2526549, 'Billion Btu', 697991, 'Billion Btu'),
 (87, 'CA', 2009, 120.100202, 'million metric tons CO2', 18.68, 'Dollars per million Btu', 36961, 'Thousand', 2490620, 'Billion Btu', 639651, 'Billion Btu'),
 (88, 'CA', 2008, 139.628142, 'million metric tons CO2', 23.25, 'Dollars per million Btu', 36604, 'Thousand', 2518661, 'Billion Btu', 590479, 'Billion Btu'),
 (89, 'CA', 2007, 147.430252, 'million metric tons CO2', 20.15, 'Dollars per million Btu', 36250, 'Thousand', 2617351, 'Billion Btu', 619334, 'Billion Btu'),
 (90, 'CA', 2006, 145.782018, 'million metric tons CO2', 19.4, 'Dollars per million Btu', 36021, 'Thousand', 2799909, 'Billion Btu', 816337, 'Billion Btu'),
 (91, 'CA', 2005, 143.332446, 'million metric tons CO2', 17.46, 'Dollars per million Btu', 35828, 'Thousand', 2807510, 'Billion Btu', 738900, 'Billion Btu'),
 (92, 'CA', 2004, 141.664798, 'million metric tons CO2', 15.17, 'Dollars per million Btu', 35575, 'Thousand', 2761999, 'Billion Btu', 696234, 'Billion Btu'),
 (93, 'CA', 2003, 139.358938, 'million metric tons CO2', 13.83, 'Dollars per million Btu', 35253, 'Thousand', 2902532, 'Billion Btu', 718110, 'Billion Btu'),
 (94, 'CA', 2002, 138.490682, 'million metric tons CO2', 12.07, 'Dollars per million Btu', 34872, 'Thousand', 2925186, 'Billion Btu', 675131, 'Billion Btu'),
 (95, 'CA', 2001, 133.630128, 'million metric tons CO2', 13.0, 'Dollars per million Btu', 34479, 'Thousand', 2875228, 'Billion Btu', 607234, 'Billion Btu'),
 (96, 'CA', 2000, 142.242532, 'million metric tons CO2', 12.05, 'Dollars per million Btu', 33988, 'Thousand', 3066949, 'Billion Btu', 735871, 'Billion Btu'),
 (97, 'CA', 1999, 136.122518, 'million metric tons CO2', 10.04, 'Dollars per million Btu', 33499, 'Thousand', 3102915, 'Billion Btu', 759406, 'Billion Btu'),
 (98, 'CA', 1998, 133.741224, 'million metric tons CO2', 9.32, 'Dollars per million Btu', 32988, 'Thousand', 3190783, 'Billion Btu', 832334, 'Billion Btu'),
 (99, 'CA', 1997, 134.474292, 'million metric tons CO2', 10.36, 'Dollars per million Btu', 32486, 'Thousand', 3048183, 'Billion Btu', 759731, 'Billion Btu'),
 (100, 'CO', 2016, 115.088298, 'million metric tons CO2', 15.77, 'Dollars per million Btu', 5541, 'Thousand', 3078173, 'Billion Btu', 125412, 'Billion Btu'),
 (101, 'CO', 2015, 120.142812, 'million metric tons CO2', 17.19, 'Dollars per million Btu', 5452, 'Thousand', 3193430, 'Billion Btu', 102732, 'Billion Btu'),
 (102, 'CO', 2014, 123.161802, 'million metric tons CO2', 21.29, 'Dollars per million Btu', 5351, 'Thousand', 3060817, 'Billion Btu', 108091, 'Billion Btu'),
 (103, 'CO', 2013, 120.908517, 'million metric tons CO2', 21.13, 'Dollars per million Btu', 5270, 'Thousand', 2834198, 'Billion Btu', 99785, 'Billion Btu'),
 (104, 'CO', 2012, 123.201027, 'million metric tons CO2', 21.8, 'Dollars per million Btu', 5194, 'Thousand', 2921831, 'Billion Btu', 85723, 'Billion Btu'),
 (105, 'CO', 2011, 129.930038, 'million metric tons CO2', 21.28, 'Dollars per million Btu', 5122, 'Thousand', 2749591, 'Billion Btu', 85169, 'Billion Btu'),
 (106, 'CO', 2010, 132.767419, 'million metric tons CO2', 17.46, 'Dollars per million Btu', 5048, 'Thousand', 2561382, 'Billion Btu', 62321, 'Billion Btu'),
 (107, 'CO', 2009, 120.100202, 'million metric tons CO2', 15.48, 'Dollars per million Btu', 4972, 'Thousand', 2497428, 'Billion Btu', 62932, 'Billion Btu'),
 (108, 'CO', 2008, 139.628142, 'million metric tons CO2', 19.81, 'Dollars per million Btu', 4890, 'Thousand', 2466361, 'Billion Btu', 63044, 'Billion Btu'),
 (109, 'CO', 2007, 147.430252, 'million metric tons CO2', 17.06, 'Dollars per million Btu', 4804, 'Thousand', 2359097, 'Billion Btu', 39490, 'Billion Btu'),
 (110, 'CO', 2006, 145.782018, 'million metric tons CO2', 16.94, 'Dollars per million Btu', 4720, 'Thousand', 2289963, 'Billion Btu', 35112, 'Billion Btu'),
 (111, 'CO', 2005, 143.332446, 'million metric tons CO2', 15.15, 'Dollars per million Btu', 4632, 'Thousand', 2246251, 'Billion Btu', 31449, 'Billion Btu'),
 (112, 'CO', 2004, 141.664798, 'million metric tons CO2', 12.48, 'Dollars per million Btu', 4575, 'Thousand', 2194135, 'Billion Btu', 22263, 'Billion Btu'),
 (113, 'CO', 2003, 139.358938, 'million metric tons CO2', 10.78, 'Dollars per million Btu', 4529, 'Thousand', 2028512, 'Billion Btu', 21650, 'Billion Btu'),
 (114, 'CO', 2002, 138.490682, 'million metric tons CO2', 9.6, 'Dollars per million Btu', 4490, 'Thousand', 1926698, 'Billion Btu', 20880, 'Billion Btu'),
 (115, 'CO', 2001, 133.630128, 'million metric tons CO2', 10.72, 'Dollars per million Btu', 4426, 'Thousand', 1736326, 'Billion Btu', 23575, 'Billion Btu'),
 (116, 'CO', 2000, 142.242532, 'million metric tons CO2', 10.25, 'Dollars per million Btu', 4327, 'Thousand', 1586157, 'Billion Btu', 26935, 'Billion Btu'),
 (117, 'CO', 1999, 136.122518, 'million metric tons CO2', 8.74, 'Dollars per million Btu', 4226, 'Thousand', 1568045, 'Billion Btu', 27918, 'Billion Btu'),
 (118, 'CO', 1998, 133.741224, 'million metric tons CO2', 8.13, 'Dollars per million Btu', 4117, 'Thousand', 1551668, 'Billion Btu', 26130, 'Billion Btu'),
 (119, 'CO', 1997, 134.474292, 'million metric tons CO2', 8.79, 'Dollars per million Btu', 4018, 'Thousand', 1470607, 'Billion Btu', 33190, 'Billion Btu'),
 (120, 'CT', 2016, 115.088298, 'million metric tons CO2', 21.89, 'Dollars per million Btu', 3579, 'Thousand', 204856, 'Billion Btu', 31493, 'Billion Btu'),
 (121, 'CT', 2015, 120.142812, 'million metric tons CO2', 23.31, 'Dollars per million Btu', 3588, 'Thousand', 211889, 'Billion Btu', 29805, 'Billion Btu'),
 (122, 'CT', 2014, 123.161802, 'million metric tons CO2', 27.96, 'Dollars per million Btu', 3595, 'Thousand', 197800, 'Billion Btu', 32123, 'Billion Btu'),
 (123, 'CT', 2013, 120.908517, 'million metric tons CO2', 27.77, 'Dollars per million Btu', 3595, 'Thousand', 207893, 'Billion Btu', 29428, 'Billion Btu'),
 (124, 'CT', 2012, 123.201027, 'million metric tons CO2', 28.66, 'Dollars per million Btu', 3594, 'Thousand', 205475, 'Billion Btu', 26515, 'Billion Btu'),
 (125, 'CT', 2011, 129.930038, 'million metric tons CO2', 28.18, 'Dollars per million Btu', 3588, 'Thousand', 196367, 'Billion Btu', 29698, 'Billion Btu'),
 (126, 'CT', 2010, 132.767419, 'million metric tons CO2', 25.64, 'Dollars per million Btu', 3579, 'Thousand', 204189, 'Billion Btu', 29114, 'Billion Btu'),
 (127, 'CT', 2009, 120.100202, 'million metric tons CO2', 23.65, 'Dollars per million Btu', 3562, 'Thousand', 203640, 'Billion Btu', 29421, 'Billion Btu'),

In [660]:
# Closing all currently checked in database connections.
engine.dispose()

In [661]:
# Create a Connection object 
con = sqlite3.connect('/Users/admin/Desktop/us_energy/us-energy-analysis/assets/db/us_energy.sqlite')

In [662]:
# Cursor object to fetch results
cur = con.cursor()

In [663]:
# Disable Foreign Key
cur.execute('PRAGMA foreign_keys=off')

In [664]:
# Open a Transaction
cur.execute('BEGIN TRANSACTION;')

In [665]:
# Rename the "state_coordinates" to "old_table"
cur.execute('ALTER TABLE final_combine_table RENAME TO old_table;')

In [666]:
# Create a new table with the same name "final_combine_table"
cur.execute('CREATE TABLE final_combine_table (id Integer PRIMARY KEY NOT NULL, State Text, Year Integer, Total_co2_emission Float,CO2_Unit Text,Average_Price Float, Price_Unit TEXT, resident_population BIGINT, Pop_Unit TEXT, Total_energy BIGINT, ENERGY_Unit TEXT, Total_renewable_energy BIGINT,Renew_Unit TEXT);')

In [667]:
# Insert "old_table" data into the newly created table "state_coordinates"
cur.execute('INSERT INTO final_combine_table SELECT * FROM old_table;')

In [668]:
# Delete the "old_table"
cur.execute('DROP TABLE old_table;')

In [669]:
# Commit the changes to the database "us_energy.sqlite"
cur.execute('COMMIT TRANSACTION;')

In [670]:
# Enabling the Foreign Key
cur.execute('PRAGMA foreign_keys=on;')

In [671]:
# Close the database connection
cur.close()
conn.close()

In [672]:
# Execute a Query to check if the table has been imported successfully 
engine.execute('SELECT * FROM final_combine_table').fetchall()

[(0, 'AL', 2016, 115.088298, 'million metric tons CO2', 14.81, 'Dollars per million Btu', 4865, 'Thousand', 1124482, 'Billion Btu', 235494, 'Billion Btu'),
 (1, 'AL', 2015, 120.142812, 'million metric tons CO2', 15.68, 'Dollars per million Btu', 4853, 'Thousand', 1269743, 'Billion Btu', 261340, 'Billion Btu'),
 (2, 'AL', 2014, 123.161802, 'million metric tons CO2', 18.62, 'Dollars per million Btu', 4842, 'Thousand', 1367345, 'Billion Btu', 268551, 'Billion Btu'),
 (3, 'AL', 2013, 120.908517, 'million metric tons CO2', 18.89, 'Dollars per million Btu', 4830, 'Thousand', 1478402, 'Billion Btu', 310608, 'Billion Btu'),
 (4, 'AL', 2012, 123.201027, 'million metric tons CO2', 19.86, 'Dollars per million Btu', 4816, 'Thousand', 1443558, 'Billion Btu', 241822, 'Billion Btu'),
 (5, 'AL', 2011, 129.930038, 'million metric tons CO2', 20.06, 'Dollars per million Btu', 4799, 'Thousand', 1410745, 'Billion Btu', 254867, 'Billion Btu'),
 (6, 'AL', 2010, 132.767419, 'million metric tons CO2', 17.8, 'Dollars per million Btu', 4785, 'Thousand', 1429505, 'Billion Btu', 240913, 'Billion Btu'),
 (7, 'AL', 2009, 120.100202, 'million metric tons CO2', 16.55, 'Dollars per million Btu', 4758, 'Thousand', 1449253, 'Billion Btu', 264487, 'Billion Btu'),
 (8, 'AL', 2008, 139.628142, 'million metric tons CO2', 19.22, 'Dollars per million Btu', 4718, 'Thousand', 1482792, 'Billion Btu', 233379, 'Billion Btu'),
 (9, 'AL', 2007, 147.430252, 'million metric tons CO2', 16.06, 'Dollars per million Btu', 4673, 'Thousand', 1408105, 'Billion Btu', 228160, 'Billion Btu'),
 (10, 'AL', 2006, 145.782018, 'million metric tons CO2', 14.96, 'Dollars per million Btu', 4629, 'Thousand', 1413493, 'Billion Btu', 266153, 'Billion Btu'),
 (11, 'AL', 2005, 143.332446, 'million metric tons CO2', 13.56, 'Dollars per million Btu', 4570, 'Thousand', 1502435, 'Billion Btu', 279600, 'Billion Btu'),
 (12, 'AL', 2004, 141.664798, 'million metric tons CO2', 11.27, 'Dollars per million Btu', 4531, 'Thousand', 1544007, 'Billion Btu', 290697, 'Billion Btu'),
 (13, 'AL', 2003, 139.358938, 'million metric tons CO2', 9.98, 'Dollars per million Btu', 4503, 'Thousand', 1521048, 'Billion Btu', 283428, 'Billion Btu'),
 (14, 'AL', 2002, 138.490682, 'million metric tons CO2', 9.16, 'Dollars per million Btu', 4480, 'Thousand', 1486477, 'Billion Btu', 252689, 'Billion Btu'),
 (15, 'AL', 2001, 133.630128, 'million metric tons CO2', 9.45, 'Dollars per million Btu', 4468, 'Thousand', 1484590, 'Billion Btu', 251523, 'Billion Btu'),
 (16, 'AL', 2000, 142.242532, 'million metric tons CO2', 8.78, 'Dollars per million Btu', 4452, 'Thousand', 1539601, 'Billion Btu', 263303, 'Billion Btu'),
 (17, 'AL', 1999, 136.122518, 'million metric tons CO2', 7.58, 'Dollars per million Btu', 4430, 'Thousand', 1578642, 'Billion Btu', 290195, 'Billion Btu'),
 (18, 'AL', 1998, 133.741224, 'million metric tons CO2', 7.33, 'Dollars per million Btu', 4405, 'Thousand', 1672363, 'Billion Btu', 317065, 'Billion Btu'),
 (19, 'AL', 1997, 134.474292, 'million metric tons CO2', 7.52, 'Dollars per million Btu', 4368, 'Thousand', 1708520, 'Billion Btu', 299675, 'Billion Btu'),
 (20, 'AK', 2016, 115.088298, 'million metric tons CO2', 16.63, 'Dollars per million Btu', 742, 'Thousand', 1433116, 'Billion Btu', 19428, 'Billion Btu'),
 (21, 'AK', 2015, 120.142812, 'million metric tons CO2', 18.82, 'Dollars per million Btu', 738, 'Thousand', 1424762, 'Billion Btu', 19209, 'Billion Btu'),
 (22, 'AK', 2014, 123.161802, 'million metric tons CO2', 24.83, 'Dollars per million Btu', 736, 'Thousand', 1474609, 'Billion Btu', 19826, 'Billion Btu'),
 (23, 'AK', 2013, 120.908517, 'million metric tons CO2', 24.92, 'Dollars per million Btu', 737, 'Thousand', 1513406, 'Billion Btu', 18664, 'Billion Btu'),
 (24, 'AK', 2012, 123.201027, 'million metric tons CO2', 25.44, 'Dollars per million Btu', 730, 'Thousand', 1563461, 'Billion Btu', 17719, 'Billion Btu'),
 (25, 'AK', 2011, 129.930038, 'million metric tons CO2', 25.13, 'Dollars per million Btu', 722, 'Thousand', 1642015, 'Billion Btu', 15762, 'Billion Btu'),
 (26, 'AK', 2010, 132.767419, 'million metric tons CO2', 20.37, 'Dollars per million Btu', 714, 'Thousand', 1738219, 'Billion Btu', 16537, 'Billion Btu'),
 (27, 'AK', 2009, 120.100202, 'million metric tons CO2', 18.22, 'Dollars per million Btu', 699, 'Thousand', 1853317, 'Billion Btu', 15685, 'Billion Btu'),
 (28, 'AK', 2008, 139.628142, 'million metric tons CO2', 23.91, 'Dollars per million Btu', 687, 'Thousand', 1932755, 'Billion Btu', 12913, 'Billion Btu'),
 (29, 'AK', 2007, 147.430252, 'million metric tons CO2', 17.94, 'Dollars per million Btu', 680, 'Thousand', 2051639, 'Billion Btu', 14037, 'Billion Btu'),
 (30, 'AK', 2006, 145.782018, 'million metric tons CO2', 16.61, 'Dollars per million Btu', 675, 'Thousand', 2100329, 'Billion Btu', 13298, 'Billion Btu'),
 (31, 'AK', 2005, 143.332446, 'million metric tons CO2', 13.99, 'Dollars per million Btu', 667, 'Thousand', 2415039, 'Billion Btu', 15866, 'Billion Btu'),
 (32, 'AK', 2004, 141.664798, 'million metric tons CO2', 11.07, 'Dollars per million Btu', 659, 'Thousand', 2512619, 'Billion Btu', 18416, 'Billion Btu'),
 (33, 'AK', 2003, 139.358938, 'million metric tons CO2', 9.08, 'Dollars per million Btu', 648, 'Thousand', 2660210, 'Billion Btu', 19374, 'Billion Btu'),
 (34, 'AK', 2002, 138.490682, 'million metric tons CO2', 7.78, 'Dollars per million Btu', 642, 'Thousand', 2658368, 'Billion Btu', 17922, 'Billion Btu'),
 (35, 'AK', 2001, 133.630128, 'million metric tons CO2', 8.18, 'Dollars per million Btu', 634, 'Thousand', 2630790, 'Billion Btu', 16974, 'Billion Btu'),
 (36, 'AK', 2000, 142.242532, 'million metric tons CO2', 8.03, 'Dollars per million Btu', 628, 'Thousand', 2645900, 'Billion Btu', 12204, 'Billion Btu'),
 (37, 'AK', 1999, 136.122518, 'million metric tons CO2', 6.17, 'Dollars per million Btu', 625, 'Thousand', 2797459, 'Billion Btu', 10212, 'Billion Btu'),
 (38, 'AK', 1998, 133.741224, 'million metric tons CO2', 5.8, 'Dollars per million Btu', 620, 'Thousand', 3067133, 'Billion Btu', 13291, 'Billion Btu'),
 (39, 'AK', 1997, 134.474292, 'million metric tons CO2', 6.74, 'Dollars per million Btu', 613, 'Thousand', 3331780, 'Billion Btu', 14994, 'Billion Btu'),
 (40, 'AZ', 2016, 115.088298, 'million metric tons CO2', 20.65, 'Dollars per million Btu', 6945, 'Thousand', 593132, 'Billion Btu', 130858, 'Billion Btu'),
 (41, 'AZ', 2015, 120.142812, 'million metric tons CO2', 22.47, 'Dollars per million Btu', 6834, 'Thousand', 614524, 'Billion Btu', 120715, 'Billion Btu'),
 (42, 'AZ', 2014, 123.161802, 'million metric tons CO2', 25.77, 'Dollars per million Btu', 6734, 'Thousand', 631852, 'Billion Btu', 114133, 'Billion Btu'),
 (43, 'AZ', 2013, 120.908517, 'million metric tons CO2', 25.89, 'Dollars per million Btu', 6635, 'Thousand', 591410, 'Billion Btu', 98874, 'Billion Btu'),
 (44, 'AZ', 2012, 123.201027, 'million metric tons CO2', 26.19, 'Dollars per million Btu', 6557, 'Thousand', 594938, 'Billion Btu', 93042, 'Billion Btu'),
 (45, 'AZ', 2011, 129.930038, 'million metric tons CO2', 25.37, 'Dollars per million Btu', 6473, 'Thousand', 615323, 'Billion Btu', 105082, 'Billion Btu'),
 (46, 'AZ', 2010, 132.767419, 'million metric tons CO2', 22.32, 'Dollars per million Btu', 6408, 'Thousand', 579778, 'Billion Btu', 77419, 'Billion Btu'),
 (47, 'AZ', 2009, 120.100202, 'million metric tons CO2', 20.14, 'Dollars per million Btu', 6343, 'Thousand', 563061, 'Billion Btu', 73117, 'Billion Btu'),
 (48, 'AZ', 2008, 139.628142, 'million metric tons CO2', 23.95, 'Dollars per million Btu', 6280, 'Thousand', 576899, 'Billion Btu', 88850, 'Billion Btu'),
 (49, 'AZ', 2007, 147.430252, 'million metric tons CO2', 20.87, 'Dollars per million Btu', 6168, 'Thousand', 538976, 'Billion Btu', 79355, 'Billion Btu'),
 (50, 'AZ', 2006, 145.782018, 'million metric tons CO2', 19.7, 'Dollars per million Btu', 6029, 'Thousand', 511638, 'Billion Btu', 80772, 'Billion Btu'),
 (51, 'AZ', 2005, 143.332446, 'million metric tons CO2', 17.87, 'Dollars per million Btu', 5839, 'Thousand', 611615, 'Billion Btu', 78333, 'Billion Btu'),
 (52, 'AZ', 2004, 141.664798, 'million metric tons CO2', 15.36, 'Dollars per million Btu', 5652, 'Thousand', 653416, 'Billion Btu', 81376, 'Billion Btu'),
 (53, 'AZ', 2003, 139.358938, 'million metric tons CO2', 13.86, 'Dollars per million Btu', 5510, 'Thousand', 643921, 'Billion Btu', 83079, 'Billion Btu'),
 (54, 'AZ', 2002, 138.490682, 'million metric tons CO2', 12.39, 'Dollars per million Btu', 5396, 'Thousand', 689876, 'Billion Btu', 86880, 'Billion Btu'),
 (55, 'AZ', 2001, 133.630128, 'million metric tons CO2', 12.82, 'Dollars per million Btu', 5273, 'Thousand', 684436, 'Billion Btu', 90513, 'Billion Btu'),
 (56, 'AZ', 2000, 142.242532, 'million metric tons CO2', 12.94, 'Dollars per million Btu', 5161, 'Thousand', 705102, 'Billion Btu', 100776, 'Billion Btu'),
 (57, 'AZ', 1999, 136.122518, 'million metric tons CO2', 11.24, 'Dollars per million Btu', 5024, 'Thousand', 691730, 'Billion Btu', 114876, 'Billion Btu'),
 (58, 'AZ', 1998, 133.741224, 'million metric tons CO2', 10.83, 'Dollars per million Btu', 4883, 'Thousand', 693182, 'Billion Btu', 126648, 'Billion Btu'),
 (59, 'AZ', 1997, 134.474292, 'million metric tons CO2', 11.76, 'Dollars per million Btu', 4737, 'Thousand', 706668, 'Billion Btu', 141607, 'Billion Btu'),
 (60, 'AR', 2016, 115.088298, 'million metric tons CO2', 14.6, 'Dollars per million Btu', 2990, 'Thousand', 1130117, 'Billion Btu', 117959, 'Billion Btu'),
 (61, 'AR', 2015, 120.142812, 'million metric tons CO2', 15.87, 'Dollars per million Btu', 2978, 'Thousand', 1319553, 'Billion Btu', 115780, 'Billion Btu'),
 (62, 'AR', 2014, 123.161802, 'million metric tons CO2', 18.86, 'Dollars per million Btu', 2968, 'Thousand', 1440726, 'Billion Btu', 116541, 'Billion Btu'),
 (63, 'AR', 2013, 120.908517, 'million metric tons CO2', 19.29, 'Dollars per million Btu', 2960, 'Thousand', 1434515, 'Billion Btu', 116746, 'Billion Btu'),
 (64, 'AR', 2012, 123.201027, 'million metric tons CO2', 19.82, 'Dollars per million Btu', 2952, 'Thousand', 1466389, 'Billion Btu', 111220, 'Billion Btu'),
 (65, 'AR', 2011, 129.930038, 'million metric tons CO2', 19.59, 'Dollars per million Btu', 2940, 'Thousand', 1385343, 'Billion Btu', 119758, 'Billion Btu'),
 (66, 'AR', 2010, 132.767419, 'million metric tons CO2', 16.86, 'Dollars per million Btu', 2922, 'Thousand', 1250560, 'Billion Btu', 123317, 'Billion Btu'),
 (67, 'AR', 2009, 120.100202, 'million metric tons CO2', 15.64, 'Dollars per million Btu', 2897, 'Thousand', 1007445, 'Billion Btu', 124205, 'Billion Btu'),
 (68, 'AR', 2008, 139.628142, 'million metric tons CO2', 19.96, 'Dollars per million Btu', 2875, 'Thousand', 761611, 'Billion Btu', 123354, 'Billion Btu'),
 (69, 'AR', 2007, 147.430252, 'million metric tons CO2', 16.68, 'Dollars per million Btu', 2849, 'Thousand', 593930, 'Billion Btu', 120733, 'Billion Btu'),
 (70, 'AR', 2006, 145.782018, 'million metric tons CO2', 15.78, 'Dollars per million Btu', 2822, 'Thousand', 572694, 'Billion Btu', 99990, 'Billion Btu'),
 (71, 'AR', 2005, 143.332446, 'million metric tons CO2', 14.46, 'Dollars per million Btu', 2781, 'Thousand', 484786, 'Billion Btu', 112451, 'Billion Btu'),
 (72, 'AR', 2004, 141.664798, 'million metric tons CO2', 11.96, 'Dollars per million Btu', 2750, 'Thousand', 503242, 'Billion Btu', 112915, 'Billion Btu'),
 (73, 'AR', 2003, 139.358938, 'million metric tons CO2', 10.23, 'Dollars per million Btu', 2725, 'Thousand', 478389, 'Billion Btu', 107905, 'Billion Btu'),
 (74, 'AR', 2002, 138.490682, 'million metric tons CO2', 9.39, 'Dollars per million Btu', 2706, 'Thousand', 469275, 'Billion Btu', 108618, 'Billion Btu'),
 (75, 'AR', 2001, 133.630128, 'million metric tons CO2', 10.2, 'Dollars per million Btu', 2692, 'Thousand', 462934, 'Billion Btu', 94001, 'Billion Btu'),
 (76, 'AR', 2000, 142.242532, 'million metric tons CO2', 9.47, 'Dollars per million Btu', 2679, 'Thousand', 447405, 'Billion Btu', 108634, 'Billion Btu'),
 (77, 'AR', 1999, 136.122518, 'million metric tons CO2', 7.9, 'Dollars per million Btu', 2652, 'Thousand', 461717, 'Billion Btu', 110822, 'Billion Btu'),
 (78, 'AR', 1998, 133.741224, 'million metric tons CO2', 7.71, 'Dollars per million Btu', 2626, 'Thousand', 492864, 'Billion Btu', 114927, 'Billion Btu'),
 (79, 'AR', 1997, 134.474292, 'million metric tons CO2', 8.24, 'Dollars per million Btu', 2601, 'Thousand', 534963, 'Billion Btu', 124045, 'Billion Btu'),
 (80, 'CA', 2016, 115.088298, 'million metric tons CO2', 19.9, 'Dollars per million Btu', 39209, 'Thousand', 2431124, 'Billion Btu', 903915, 'Billion Btu'),
 (81, 'CA', 2015, 120.142812, 'million metric tons CO2', 21.88, 'Dollars per million Btu', 38953, 'Thousand', 2361858, 'Billion Btu', 719166, 'Billion Btu'),
 (82, 'CA', 2014, 123.161802, 'million metric tons CO2', 25.51, 'Dollars per million Btu', 38625, 'Thousand', 2383159, 'Billion Btu', 721739, 'Billion Btu'),
 (83, 'CA', 2013, 120.908517, 'million metric tons CO2', 25.08, 'Dollars per million Btu', 38281, 'Thousand', 2372246, 'Billion Btu', 719604, 'Billion Btu'),
 (84, 'CA', 2012, 123.201027, 'million metric tons CO2', 25.13, 'Dollars per million Btu', 37961, 'Thousand', 2317708, 'Billion Btu', 677346, 'Billion Btu'),
 (85, 'CA', 2011, 129.930038, 'million metric tons CO2', 24.5, 'Dollars per million Btu', 37642, 'Thousand', 2632438, 'Billion Btu', 806477, 'Billion Btu'),
 (86, 'CA', 2010, 132.767419, 'million metric tons CO2', 21.13, 'Dollars per million Btu', 37321, 'Thousand', 2526549, 'Billion Btu', 697991, 'Billion Btu'),
 (87, 'CA', 2009, 120.100202, 'million metric tons CO2', 18.68, 'Dollars per million Btu', 36961, 'Thousand', 2490620, 'Billion Btu', 639651, 'Billion Btu'),
 (88, 'CA', 2008, 139.628142, 'million metric tons CO2', 23.25, 'Dollars per million Btu', 36604, 'Thousand', 2518661, 'Billion Btu', 590479, 'Billion Btu'),
 (89, 'CA', 2007, 147.430252, 'million metric tons CO2', 20.15, 'Dollars per million Btu', 36250, 'Thousand', 2617351, 'Billion Btu', 619334, 'Billion Btu'),
 (90, 'CA', 2006, 145.782018, 'million metric tons CO2', 19.4, 'Dollars per million Btu', 36021, 'Thousand', 2799909, 'Billion Btu', 816337, 'Billion Btu'),
 (91, 'CA', 2005, 143.332446, 'million metric tons CO2', 17.46, 'Dollars per million Btu', 35828, 'Thousand', 2807510, 'Billion Btu', 738900, 'Billion Btu'),
 (92, 'CA', 2004, 141.664798, 'million metric tons CO2', 15.17, 'Dollars per million Btu', 35575, 'Thousand', 2761999, 'Billion Btu', 696234, 'Billion Btu'),
 (93, 'CA', 2003, 139.358938, 'million metric tons CO2', 13.83, 'Dollars per million Btu', 35253, 'Thousand', 2902532, 'Billion Btu', 718110, 'Billion Btu'),
 (94, 'CA', 2002, 138.490682, 'million metric tons CO2', 12.07, 'Dollars per million Btu', 34872, 'Thousand', 2925186, 'Billion Btu', 675131, 'Billion Btu'),
 (95, 'CA', 2001, 133.630128, 'million metric tons CO2', 13.0, 'Dollars per million Btu', 34479, 'Thousand', 2875228, 'Billion Btu', 607234, 'Billion Btu'),
 (96, 'CA', 2000, 142.242532, 'million metric tons CO2', 12.05, 'Dollars per million Btu', 33988, 'Thousand', 3066949, 'Billion Btu', 735871, 'Billion Btu'),
 (97, 'CA', 1999, 136.122518, 'million metric tons CO2', 10.04, 'Dollars per million Btu', 33499, 'Thousand', 3102915, 'Billion Btu', 759406, 'Billion Btu'),
 (98, 'CA', 1998, 133.741224, 'million metric tons CO2', 9.32, 'Dollars per million Btu', 32988, 'Thousand', 3190783, 'Billion Btu', 832334, 'Billion Btu'),
 (99, 'CA', 1997, 134.474292, 'million metric tons CO2', 10.36, 'Dollars per million Btu', 32486, 'Thousand', 3048183, 'Billion Btu', 759731, 'Billion Btu'),
 (100, 'CO', 2016, 115.088298, 'million metric tons CO2', 15.77, 'Dollars per million Btu', 5541, 'Thousand', 3078173, 'Billion Btu', 125412, 'Billion Btu'),
 (101, 'CO', 2015, 120.142812, 'million metric tons CO2', 17.19, 'Dollars per million Btu', 5452, 'Thousand', 3193430, 'Billion Btu', 102732, 'Billion Btu'),
 (102, 'CO', 2014, 123.161802, 'million metric tons CO2', 21.29, 'Dollars per million Btu', 5351, 'Thousand', 3060817, 'Billion Btu', 108091, 'Billion Btu'),
 (103, 'CO', 2013, 120.908517, 'million metric tons CO2', 21.13, 'Dollars per million Btu', 5270, 'Thousand', 2834198, 'Billion Btu', 99785, 'Billion Btu'),
 (104, 'CO', 2012, 123.201027, 'million metric tons CO2', 21.8, 'Dollars per million Btu', 5194, 'Thousand', 2921831, 'Billion Btu', 85723, 'Billion Btu'),
 (105, 'CO', 2011, 129.930038, 'million metric tons CO2', 21.28, 'Dollars per million Btu', 5122, 'Thousand', 2749591, 'Billion Btu', 85169, 'Billion Btu'),
 (106, 'CO', 2010, 132.767419, 'million metric tons CO2', 17.46, 'Dollars per million Btu', 5048, 'Thousand', 2561382, 'Billion Btu', 62321, 'Billion Btu'),
 (107, 'CO', 2009, 120.100202, 'million metric tons CO2', 15.48, 'Dollars per million Btu', 4972, 'Thousand', 2497428, 'Billion Btu', 62932, 'Billion Btu'),
 (108, 'CO', 2008, 139.628142, 'million metric tons CO2', 19.81, 'Dollars per million Btu', 4890, 'Thousand', 2466361, 'Billion Btu', 63044, 'Billion Btu'),
 (109, 'CO', 2007, 147.430252, 'million metric tons CO2', 17.06, 'Dollars per million Btu', 4804, 'Thousand', 2359097, 'Billion Btu', 39490, 'Billion Btu'),
 (110, 'CO', 2006, 145.782018, 'million metric tons CO2', 16.94, 'Dollars per million Btu', 4720, 'Thousand', 2289963, 'Billion Btu', 35112, 'Billion Btu'),
 (111, 'CO', 2005, 143.332446, 'million metric tons CO2', 15.15, 'Dollars per million Btu', 4632, 'Thousand', 2246251, 'Billion Btu', 31449, 'Billion Btu'),
 (112, 'CO', 2004, 141.664798, 'million metric tons CO2', 12.48, 'Dollars per million Btu', 4575, 'Thousand', 2194135, 'Billion Btu', 22263, 'Billion Btu'),
 (113, 'CO', 2003, 139.358938, 'million metric tons CO2', 10.78, 'Dollars per million Btu', 4529, 'Thousand', 2028512, 'Billion Btu', 21650, 'Billion Btu'),
 (114, 'CO', 2002, 138.490682, 'million metric tons CO2', 9.6, 'Dollars per million Btu', 4490, 'Thousand', 1926698, 'Billion Btu', 20880, 'Billion Btu'),
 (115, 'CO', 2001, 133.630128, 'million metric tons CO2', 10.72, 'Dollars per million Btu', 4426, 'Thousand', 1736326, 'Billion Btu', 23575, 'Billion Btu'),
 (116, 'CO', 2000, 142.242532, 'million metric tons CO2', 10.25, 'Dollars per million Btu', 4327, 'Thousand', 1586157, 'Billion Btu', 26935, 'Billion Btu'),
 (117, 'CO', 1999, 136.122518, 'million metric tons CO2', 8.74, 'Dollars per million Btu', 4226, 'Thousand', 1568045, 'Billion Btu', 27918, 'Billion Btu'),
 (118, 'CO', 1998, 133.741224, 'million metric tons CO2', 8.13, 'Dollars per million Btu', 4117, 'Thousand', 1551668, 'Billion Btu', 26130, 'Billion Btu'),
 (119, 'CO', 1997, 134.474292, 'million metric tons CO2', 8.79, 'Dollars per million Btu', 4018, 'Thousand', 1470607, 'Billion Btu', 33190, 'Billion Btu'),
 (120, 'CT', 2016, 115.088298, 'million metric tons CO2', 21.89, 'Dollars per million Btu', 3579, 'Thousand', 204856, 'Billion Btu', 31493, 'Billion Btu'),
 (121, 'CT', 2015, 120.142812, 'million metric tons CO2', 23.31, 'Dollars per million Btu', 3588, 'Thousand', 211889, 'Billion Btu', 29805, 'Billion Btu'),
 (122, 'CT', 2014, 123.161802, 'million metric tons CO2', 27.96, 'Dollars per million Btu', 3595, 'Thousand', 197800, 'Billion Btu', 32123, 'Billion Btu'),
 (123, 'CT', 2013, 120.908517, 'million metric tons CO2', 27.77, 'Dollars per million Btu', 3595, 'Thousand', 207893, 'Billion Btu', 29428, 'Billion Btu'),
 (124, 'CT', 2012, 123.201027, 'million metric tons CO2', 28.66, 'Dollars per million Btu', 3594, 'Thousand', 205475, 'Billion Btu', 26515, 'Billion Btu'),
 (125, 'CT', 2011, 129.930038, 'million metric tons CO2', 28.18, 'Dollars per million Btu', 3588, 'Thousand', 196367, 'Billion Btu', 29698, 'Billion Btu'),
 (126, 'CT', 2010, 132.767419, 'million metric tons CO2', 25.64, 'Dollars per million Btu', 3579, 'Thousand', 204189, 'Billion Btu', 29114, 'Billion Btu'),
 (127, 'CT', 2009, 120.100202, 'million metric tons CO2', 23.65, 'Dollars per million Btu', 3562, 'Thousand', 203640, 'Billion Btu', 29421, 'Billion Btu'),

In [673]:
# Closing all currently checked in database connections
engine.dispose()